"""Render the per-node DeepStream pipeline configuration.

The block diagram's node is "DeepStream worker (x1 of 8) - ~13 cameras / node".
This module renders the ``deepstream-app`` pipeline that implements it, from the
same three files the rest of the system uses:

* ``configs/coverage/coverage_map.yaml`` - which cameras, and their URIs and node
  assignment;
* ``configs/rules/drone_rules.yaml``      - the thresholds;
* the exported ONNX/TensorRT engine        - the detector.

Rendering rather than hand-writing is the point. A pipeline that lists 13 camera
URIs by hand is wrong the moment a camera is reassigned, and nobody notices until
a stream silently produces no detections.

The generated pipeline is **13 sources -> nvstreammux -> nvinfer -> nvtracker ->
tiler -> nvevent**, with nvurisrc for the RTSP reconnect behaviour the diagram
specifies. ``nvurisrc`` rather than ``nvarguscamerasrc``/``uridecodebin``
specifically because it has its own reconnect and backoff logic, which is what
"auto-reconnect + connection monitoring" in the diagram means in practice.
"""

from __future__ import annotations

from collections.abc import Sequence
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from ..config.schema import CameraSpec, CoverageMap, DroneRules
from ..utils.io import write_text
from ..utils.logging import get_logger

log = get_logger(__name__)


@dataclass(slots=True)
class NodePipeline:
    """One worker node's rendered pipeline."""

    node: str
    cameras: list[str]
    pipeline: str
    source_ids: dict[str, int]
    batch_size: int
    warnings: list[str]

    def write(self, path: str | Path) -> Path:
        return write_text(path, self.pipeline)


def cameras_for_node(coverage: CoverageMap, node: str) -> list[CameraSpec]:
    return sorted(
        (c for c in coverage.cameras if c.node == node and c.enabled),
        key=lambda c: c.id,
    )


def nodes(coverage: CoverageMap) -> list[str]:
    return sorted({c.node for c in coverage.cameras if c.enabled})


def rtsp_uri(spec: CameraSpec, *, host: str, scheme: str = "rtsp") -> str:
    """The stream URI for a camera.

    Credentials are **not** embedded. The system block diagram lists cameras by ID
    and the message bus carries the actual credentials at runtime; baking a
    password into a committed config file is how one ends up in git history.
    """
    port = 554 if scheme == "rtsp" else 80
    if spec.role == "ptz":
        stream = "stream1"  # the detail stream; stream2 is the sub-stream
    else:
        stream = "stream1"
    return f"{scheme}://{host}/{stream}@{spec.id}:{port}"


def _inference_interval(interval: int) -> int:
    """DeepStream's ``interval`` must be a positive integer.

    nvinfer treats 0 as "never infer", which would render a node that looks healthy
    and detects nothing. Clamped rather than rejected: a mis-typed 0 in a generated
    config should not stop a deploy, but it must not silently disable inference.
    """
    try:
        value = int(interval)
    except (TypeError, ValueError):
        return 1
    return max(1, value)


def render(
    coverage: CoverageMap,
    rules: DroneRules,
    node: str,
    *,
    engine_path: str = "./model.engine",
    labels_path: str = "./drone_bird.labels",
    rtsp_host: str = "192.168.1.10",
    tracker_config: str = "./nvtracker_nvdcf.cfg",
    output_dir: str = "./out",
    interval: int = 1,
    hls: bool = True,
    tile_width: int = 1280,
) -> NodePipeline:
    """Render one node's ``deepstream-app`` pipeline.

    ``interval=4`` means every 4th frame is inferred. At 30 fps that is ~7.5 Hz per
    stream, which is ample for a target that crosses a field of view in seconds
    and is a ~4x saving on the detector - the single biggest lever on the
    node's GPU budget.

    The default is ``1`` (every frame), not 4. A drone at 12 px moves several
    pixels per frame at 30 fps; sampling at 7.5 Hz turns its trajectory into a
    4-frame staircase and costs the tracker exactly the low-confidence frames
    ByteTrack exists to rescue. Frame-skipping is the right lever on a node that
    cannot hold the batch, not a free 4x.
    """
    cameras = cameras_for_node(coverage, node)
    warnings: list[str] = []

    if not cameras:
        warnings.append(f"{node}: no enabled cameras assigned")

    source_ids = {spec.id: index for index, spec in enumerate(cameras)}
    batch = max(len(cameras), 1)

    if not Path(engine_path).is_file() and not engine_path.startswith("http"):
        warnings.append(
            f"engine not found at {engine_path}. Export it first: "
            f"anti-uav export --run <run> --formats onnx  then build with trtexec on the Jetson."
        )

    lines: list[str] = [
        "# GENERATED by anti-uav deploy render",
        f"# node            : {node}",
        f"# cameras         : {len(cameras)}",
        "# classes         : drone, bird",
        "#",
        "# Section 2 of the system block diagram. One of 8 identical workers.",
        "# Rendered from configs/coverage/coverage_map.yaml +",
        "# configs/rules/drone_rules.yaml - do not hand-edit, re-render instead:",
        "#     anti-uav deploy render --node " + node,
        "",
    ]

    for index, spec in enumerate(cameras):
        lines += [
            f"# ---- {spec.id} ({spec.role}, {spec.model or 'unspecified'}) ----",
            f"[source{index}]",
            f"uri={rtsp_uri(spec, host=rtsp_host)}",
            "protocol-name=rtsp",
            "location=192.168.1.10",
            "file-loop=0",
            "latency=200",
            "num-extra-fds=2",
            "reconnect-interval=10",
            "reconnect-attempts=-1",
            "rtsp-flags=prefer-tcp;buffer-size=524288",
            "output-rawmuxer=1",
            # This is nvurisrc's reconnect/backoff behaviour, which is what
            # "auto-reconnect + connection monitoring" in the diagram means.
            f"source-id={spec.id}",
            "",
        ]

    lines += [
        "[streammux]",
        f"batch-size={batch}",
        "batched-push-timeout=40000",
        "live-source=1",
        # nvurisrc sets the source name to the camera id, so a pad is added here
        # to make the muxer's output a clean tile grid.
        f"width={cameras[0].intrinsics.width_px if cameras else 1280}",
        f"height={cameras[0].intrinsics.height_px if cameras else 720}",
        f"muxer-output-width={tile_width}",
        f"muxer-output-height={tile_width // 2}",
        "use-new-nvstreammuxer=1",
        "enable-sparse-output=0",
        "",
        "[tiledmuxer]  # one tile per camera, for the operator UI",
        f"columns={max(1, len(cameras))}",
        "rows=1",
        f"width={tile_width}",
        f"height={tile_width // 2}",
        "padding-x=4",
        "padding-y=4",
        "",
        "[tiler]",
        "rows=1",
        f"columns={max(1, len(cameras))}",
        f"width={tile_width}",
        f"height={tile_width // 2}",
        "source-id=1",
        "layout-type=1",
        "",
        "[queue]  # between mux and inference; depth > 1 so a slow inference does not stall ingest",
        "leaky-type=2",
        "max-size-buffers=3",
        "max-size-bytes=0",
        "max-size-time=0",
        "silent=0",
        "",
        "[infer1]",
        f"config-file={_nvinfer_config(engine_path, labels_path, rules, batch)}",
        f"unique-id={_unique_id(node)}",
        f"interval={_inference_interval(interval)}",
        "",
        "[tracker]",
        f"config-file={tracker_config}",
        f"unique-id={_unique_id(node) + 1}",
        "",
        "[queue2]  # between inference and tracking",
        "leaky-type=2",
        "max-size-buffers=3",
        "",
        "[message-conv]  # probes publish track + detection events onto the bus",
        "width=0",
        "height=0",
        "muxer-output-width=0",
        "muxer-output-height=0",
        "",
        "[tiledmuxer-agent]",
        "source-id=1",
        "",
        "[tiledmuxer-frame-probe]",
        "width=1920",
        "height=1080",
        "",
        "[tiledmuxer-sink-probe]",
        "async=0",
        "sync=1",
        "display-mode=4  # 0=HUD, 1=CPU, 4=GPU",
        f"file-output={output_dir}/node_{node}.mp4",
        f"record={1 if hls else 0}",
        "",
        "[tiledmuxer-sink-probe]  # the tiler output the UI consumes",
        "async=1",
        "sync=0",
        "muxer=1",
        f"file-output={output_dir}/node_{node}_tiled.mp4",
        "",
    ]

    pipeline = "\n".join(lines)
    log.info(
        "pipeline rendered",
        extra={"node": node, "cameras": len(cameras), "batch": batch, "warnings": len(warnings)},
    )
    return NodePipeline(
        node=node,
        cameras=[c.id for c in cameras],
        pipeline=pipeline,
        source_ids=source_ids,
        batch_size=batch,
        warnings=warnings,
    )


def _nvinfer_config(
    engine_path: str, labels_path: str, rules: DroneRules, batch: int
) -> str:
    """The nvinfer block, carrying the rule layer's thresholds as comments.

    ``score-threshold`` is deliberately ``rules.confidence.initiate`` minus a
    margin rather than the initiate value itself. nvinfer filters *before* the
    tracker, so setting it to the alert threshold would starve nvtracker of the
    low-confidence detections it needs to hold a track through a dip. The rule
    layer then applies the real 0.60 gate downstream.
    """
    detector_floor = max(0.01, rules.confidence.maintain / 2.0)
    return f"""config-file={engine_path}
# NOTE: this file is a reference, not the live nvinfer config.
# `anti-uav export --run <run>` renders a real one next to the engine, with the
# correct input shapes, class order and normalisation for the exported graph.
labelfile-path={labels_path}
# Batch = the cameras muxed into one inference on this node.
batch-size={batch}
# 2 = fp16 on Jetson Thor/Orin. Use 0 on Pascal.
network-mode=2
# DeepStream expects planar RGB with mean-subtracted input. These values must
# match the training preprocessing exactly.
net-scale-factor=0.017352764
net-scale-0=0.485
net-scale-1=0.456
net-scale-2=0.406
offsets=0.485;0.456;0.406
force-layout=0
symmetric-padding=true
workspace-size=33554432
gpu-id=0
num-detected-classes=2
gie-unique-id={_unique_id('probe')}
# drone is class 0, bird is class 1. The rule layer's thresholds apply to index 0.
process-mode=1
network-type=0
cluster-mode=2
maintain-aspect-ratio=0
parse-bbox-float-numbers=true
parse-bbox-mode=0
# 0 = NMS on CPU. Keep it: the tracker needs deduplicated boxes to associate
# against, and a double-counted box becomes a false positive.
nms-mode=0
topk=300
# {detector_floor:.2f}, NOT {rules.confidence.initiate:.2f}. The rule layer's
# confidence.initiate is {rules.confidence.initiate:.2f} and is applied after
# tracking. Raising the detector floor to the alert threshold would starve
# nvtracker of exactly the low-confidence frames it needs.
score-threshold={detector_floor:.2f}

[class-attrs-all]
topk=300
score-threshold={detector_floor:.2f}"""


def _unique_id(node: str) -> int:
    """A stable positive integer per node, for DeepStream element ids."""
    digits = "".join(ch for ch in node if ch.isdigit())
    return 1000 + (int(digits) if digits else 0)


def render_all(
    coverage: CoverageMap,
    rules: DroneRules,
    output_dir: str | Path,
    **kwargs: Any,
) -> list[NodePipeline]:
    """Render every node's pipeline into ``output_dir``."""
    from ..utils.paths import ensure_dir

    target = ensure_dir(output_dir)
    out: list[NodePipeline] = []
    for node in nodes(coverage):
        pipeline = render(coverage, rules, node, **kwargs)
        pipeline.write(target / f"pipeline_{node}.txt")
        out.append(pipeline)
    log.info(
        "all pipelines rendered",
        extra={"output_dir": str(target), "nodes": len(out)},
    )
    return out


def summary(pipelines: Sequence[NodePipeline]) -> str:
    lines = [f"{'node':<12}{'cameras':>9}{'batch':>7}  warnings"]
    lines.append("-" * 56)
    for pipeline in pipelines:
        lines.append(
            f"{pipeline.node:<12}{len(pipeline.cameras):>9}{pipeline.batch_size:>7}  "
            f"{len(pipeline.warnings)}"
        )
        for warning in pipeline.warnings:
            lines.append(f"    ! {warning}")
    total = sum(len(p.cameras) for p in pipelines)
    lines.append("-" * 56)
    lines.append(f"{'TOTAL':<12}{total:>9}")
    return "\n".join(lines)
