"""PTZ control over ONVIF.

Section 3 of the system block diagram's "PTZ Controller": ONVIF Profile S
absolute-move, converting target-region requests into pan/tilt/zoom commands with
velocity presets and dwell, accounting for movement and zoom settling time, and
handling overshoot and delayed movement.

The part that is easy to get wrong
----------------------------------
An absolute-move command is **asynchronous**. ``Move`` returns immediately and the
camera slews for seconds afterwards. So this controller's real job is not issuing
the command - it is knowing when the command has *taken effect*, and refusing to
issue a conflicting one before then.

``wait_for_settle`` exists for exactly that, and the scheduler's
``_settle_until`` bookkeeping is its mirror. Issuing a second move while the first
is still in flight makes the camera stop-and-restart, which costs more time than
either move alone.
"""

from __future__ import annotations

import math
import time
from collections.abc import Callable, Sequence
from dataclasses import dataclass, field
from enum import StrEnum
from typing import Any

from ...utils.geometry import normalize_angle, unwrap_bearing
from ...utils.logging import get_logger

log = get_logger(__name__)


class MoveState(StrEnum):
    IDLE = "idle"
    MOVING = "moving"
    SETTLING = "settling"
    ERROR = "error"


@dataclass(slots=True)
class PtzPose:
    """A commanded or reported camera pose."""

    yaw_deg: float
    pitch_deg: float
    zoom: float

    def as_tuple(self) -> tuple[float, float, float]:
        return (self.yaw_deg, self.pitch_deg, self.zoom)

    def to_dict(self) -> dict[str, float]:
        return {
            "yaw_deg": round(self.yaw_deg, 3),
            "pitch_deg": round(self.pitch_deg, 3),
            "zoom": round(self.zoom, 3),
        }


@dataclass(slots=True)
class MoveCommand:
    """One ONVIF absolute-move request and its predicted outcome."""

    camera_id: str
    target: PtzPose
    issued_at_s: float
    pan_delta_deg: float
    tilt_delta_deg: float
    predicted_slew_s: float
    predicted_settle_s: float
    predicted_arrival_s: float
    #: The move that will actually stop short of the target.
    effective_target: PtzPose
    onvif_options: str = ""

    def to_dict(self) -> dict[str, Any]:
        return {
            "camera_id": self.camera_id,
            "target": self.target.to_dict(),
            "effective_target": self.effective_target.to_dict(),
            "pan_delta_deg": round(self.pan_delta_deg, 3),
            "tilt_delta_deg": round(self.tilt_delta_deg, 3),
            "predicted_slew_s": round(self.predicted_slew_s, 3),
            "predicted_settle_s": round(self.predicted_settle_s, 3),
            "predicted_arrival_s": round(self.predicted_arrival_s, 3),
            "onvif_options": self.onvif_options,
        }


@dataclass(slots=True)
class PtzStatus:
    """What the controller believes about one camera."""

    camera_id: str
    pose: PtzPose
    state: MoveState = MoveState.IDLE
    command: MoveCommand | None = None
    #: Frames or seconds of residual velocity after the command, for overshoot
    #: correction.
    residual: tuple[float, float] = (0.0, 0.0)
    error: str = ""
    history: list[PtzPose] = field(default_factory=list)

    def to_dict(self) -> dict[str, Any]:
        return {
            "camera_id": self.camera_id,
            "pose": self.pose.to_dict(),
            "state": self.state.value,
            "moving": self.state is not MoveState.MOVING,
            "error": self.error,
            "command": self.command.to_dict() if self.command else None,
        }


class PtzController:
    """Issues ONVIF absolute moves and tracks when they take effect.

    ``transport`` is injectable so the whole controller can be exercised without a
    camera: pass a callable taking ``(camera_id, xml)`` and returning nothing. The
    XML is generated by :func:`build_absolute_move` so the exact ONVIF request that
    would go on the wire is inspectable and testable.
    """

    def __init__(
        self,
        coverage: Any,
        *,
        transport: Callable[[str, str], None] | None = None,
        clock: Callable[[], float] = time.monotonic,
        dwell_s: float = 0.15,
    ) -> None:
        self.coverage = coverage
        self.transport = transport
        self.clock = clock
        self.dwell_s = dwell_s
        self.status: dict[str, PtzStatus] = {}
        self.commands: list[MoveCommand] = []

    # -- capabilities ------------------------------------------------------- #

    def _limits(self, camera_id: str) -> Any:
        view = self.coverage.view(camera_id)
        if view is None or not view.is_ptz:
            raise KeyError(f"{camera_id} is not a controllable PTZ camera")
        return view.spec.ptz

    def limits(self, camera_id: str) -> dict[str, tuple[float, float]]:
        ptz = self._limits(camera_id)
        return {
            "pan": (ptz.pan_min_deg, ptz.pan_max_deg),
            "tilt": (ptz.tilt_min_deg, ptz.tilt_max_deg),
            "zoom": (ptz.zoom_min, ptz.zoom_max),
        }

    # -- movement ----------------------------------------------------------- #

    def move(
        self,
        camera_id: str,
        pose: PtzPose | tuple[float, float, float],
        *,
        wait: bool = False,
    ) -> MoveCommand:
        """Command an absolute move. Non-blocking unless ``wait=True``."""
        ptz = self._limits(camera_id)
        target = pose if isinstance(pose, PtzPose) else PtzPose(*pose)

        clamped = PtzPose(
            yaw_deg=float(_clamp(target.yaw_deg, ptz.pan_min_deg, ptz.pan_max_deg)),
            pitch_deg=float(_clamp(target.pitch_deg, ptz.tilt_min_deg, ptz.tilt_max_deg)),
            zoom=float(_clamp(target.zoom, ptz.zoom_min, ptz.zoom_max)),
        )

        current = self.pose(camera_id)
        pan_delta = abs(normalize_angle(math.radians(clamped.yaw_deg - current.yaw_deg))) * 180.0 / math.pi
        tilt_delta = abs(clamped.pitch_deg - current.pitch_deg)
        zoom_ratio = clamped.zoom / max(current.zoom, 1e-6)

        slew_s = math.hypot(
            pan_delta / max(ptz.max_pan_speed_deg_s, 1e-3),
            tilt_delta / max(ptz.max_tilt_speed_deg_s, 1e-3),
        )
        # Zoom is not a velocity-specified axis; model it as a fixed per-stop cost
        # and let it dominate when the ratio is large, which is the realistic case.
        zoom_s = abs(math.log(max(zoom_ratio, 1e-6))) * 0.45
        settle_s = ptz.settle_time_s * (1.0 + ptz.overshoot_ratio)

        # Overshoot: the camera keeps moving past the commanded pose, so plan to
        # correct rather than assume perfection.
        overshoot_pan = math.copysign(pan_delta * ptz.overshoot_ratio, clamped.yaw_deg - current.yaw_deg)
        overshoot_tilt = math.copysign(tilt_delta * ptz.overshoot_ratio, clamped.pitch_deg - current.pitch_deg)
        effective = PtzPose(
            yaw_deg=float(_clamp(clamped.yaw_deg - overshoot_pan, ptz.pan_min_deg, ptz.pan_max_deg)),
            pitch_deg=float(_clamp(clamped.pitch_deg - overshoot_tilt, ptz.tilt_min_deg, ptz.tilt_max_deg)),
            zoom=clamped.zoom,
        )

        command = MoveCommand(
            camera_id=camera_id,
            target=clamped,
            issued_at_s=self.clock(),
            pan_delta_deg=pan_delta,
            tilt_delta_deg=tilt_delta,
            predicted_slew_s=max(slew_s, zoom_s),
            predicted_settle_s=settle_s,
            predicted_arrival_s=max(slew_s, zoom_s) + settle_s,
            effective_target=effective,
            onvif_options=_describe_options(ptz, pan_delta, tilt_delta, zoom_ratio),
        )

        xml = build_absolute_move(effective, space="Absolute", speed=None)

        if self.transport is not None:
            try:
                self.transport(camera_id, xml)
            except Exception as exc:
                command.onvif_options += f" (transport error: {exc})"
                log.error("ptz transport failed", extra={"camera": camera_id, "error": str(exc)})

        self.commands.append(command)
        self.status[camera_id] = PtzStatus(
            camera_id=camera_id,
            pose=current,
            state=MoveState.MOVING,
            command=command,
            residual=(overshoot_pan, overshoot_tilt),
            error="" if self.transport is not None else "no transport configured (simulated)",
        )
        # Tell the coverage model immediately: the planner must assume the camera is
        # about to be pointing elsewhere, even before it physically moves.
        self.coverage.set_pose(camera_id, effective.yaw_deg, effective.pitch_deg, effective.zoom)

        log.info(
            "ptz move commanded",
            extra={
                "camera": camera_id,
                "pan_deg": round(pan_delta, 1),
                "tilt_deg": round(tilt_delta, 1),
                "zoom": round(zoom_ratio, 2),
                "predicted_arrival_s": round(command.predicted_arrival_s, 2),
            },
        )

        if wait:
            self.wait_for_settle(camera_id)

        return command

    def wait_for_settle(self, camera_id: str, *, timeout_s: float | None = None) -> bool:
        """Block until a commanded move has taken effect.

        Returns ``False`` on timeout. Callers must handle that: a timeout means the
        camera is not where the plan thinks, and every downstream geometric decision
        is then wrong.
        """
        status = self.status.get(camera_id)
        if status is None or status.command is None:
            return True

        limit = timeout_s if timeout_s is not None else status.command.predicted_arrival_s * 3.0
        started = self.clock()
        while self.clock() - started < limit:
            if self.poll(camera_id):
                return True
            time.sleep(0.02)

        log.warning(
            "ptz settle timed out",
            extra={
                "camera": camera_id,
                "waited_s": round(self.clock() - started, 2),
                "limit_s": round(limit, 2),
            },
        )
        return False

    def poll(self, camera_id: str) -> bool:
        """Advance the state machine one step. ``True`` when settled.

        Without a real device the state advances on the clock using the predicted
        duration, which is what makes this testable offline. With a device, feed
        the reported velocity here instead.

        ``MOVING`` -> ``SETTLING`` -> ``IDLE`` are three distinct states and all
        three must be walked: treating ``SETTLING`` as "done" would report the
        camera as ready while it is still moving, and the scheduler would then
        command a second move that cancels the first.
        """
        status = self.status.get(camera_id)
        if status is None or status.command is None:
            return True

        if status.state in {MoveState.IDLE, MoveState.ERROR}:
            return True

        elapsed = self.clock() - status.command.issued_at_s

        if status.state is MoveState.MOVING and elapsed >= status.command.predicted_slew_s:
            status.state = MoveState.SETTLING

        if status.state is MoveState.SETTLING and elapsed >= status.command.predicted_arrival_s:
            status.state = MoveState.IDLE
            status.pose = status.command.effective_target
            status.command = None
            status.residual = (0.0, 0.0)
            status.history.append(status.pose)
            log.info(
                "ptz move settled",
                extra={
                    "camera": camera_id,
                    "elapsed_s": round(elapsed, 2),
                    "pose": status.pose.to_dict(),
                },
            )
            return True

        return False

    def poll_all(self) -> dict[str, bool]:
        return {camera_id: self.poll(camera_id) for camera_id in list(self.status)}

    # -- state -------------------------------------------------------------- #

    def pose(self, camera_id: str) -> PtzPose:
        status = self.status.get(camera_id)
        if status is not None:
            return status.pose
        view = self.coverage.view(camera_id)
        if view is None:
            raise KeyError(camera_id)
        return PtzPose(view.current_yaw_deg, view.current_pitch_deg, view.current_zoom)

    def is_busy(self, camera_id: str) -> bool:
        status = self.status.get(camera_id)
        return status is not None and status.state in {MoveState.MOVING, MoveState.SETTLING}

    def busy_cameras(self) -> list[str]:
        return [camera_id for camera_id, s in self.status.items() if self.is_busy(camera_id)]

    def snapshot(self) -> list[dict[str, Any]]:
        return [self.status[c].to_dict() for c in sorted(self.status)]

    def describe(self) -> str:
        lines = [f"controlled cameras: {len(self.ptz_camera_ids())}", f"commands issued  : {len(self.commands)}"]
        busy = self.busy_cameras()
        lines.append(f"in motion       : {len(busy)}")
        for camera_id in busy:
            status = self.status[camera_id]
            command = status.command
            if command is None:
                continue
            remaining = command.predicted_arrival_s - (self.clock() - command.issued_at_s)
            lines.append(
                f"  {camera_id}: {status.state.value}, ~{max(remaining, 0.0):.2f} s remaining"
            )
        return "\n".join(lines)

    def ptz_camera_ids(self) -> list[str]:
        return [v.camera_id for v in self.coverage.views.values() if v.is_ptz]


# --------------------------------------------------------------------------- #
# ONVIF request construction
# --------------------------------------------------------------------------- #


def build_absolute_move(
    pose: PtzPose,
    *,
    space: str = "Absolute",
    speed: float | None = None,
    token: str = "",
) -> str:
    """Build the ONVIF ``ContinuousMove`` XML for an absolute pose.

    Exposed as a pure function so the exact bytes that would go on the wire are
    inspectable in a test without a camera on the network. Pan/tilt are sent in
    normalised ``[-1, 1]`` units, which is what ONVIF Profile S expects - sending
    degrees here is a classic reason a PTZ silently refuses to move.
    """
    pan = float(_clamp(pose.yaw_deg / 180.0, -1.0, 1.0))
    tilt = float(_clamp(pose.pitch_deg / 90.0, -1.0, 1.0))
    zoom = float(max(pose.zoom - 1.0, 0.0))

    speed_element = ""
    if speed is not None:
        speed_element = f"<Speed x='{speed}' y='{speed}' z='{speed}'/>"

    return (
        '<?xml version="1.0" encoding="UTF-8"?>'
        '<s:Envelope xmlns:s="http://www.w3.org/2003/05/soap-envelope"'
        ' xmlns:a="http://www.onvif.org/ver20/wsdl"'
        ' xmlns:tds="http://www.onvif.org/ver10/device/wsdl"'
        ' xmlns:ptz="http://www.onvif.org/ver20/ptz/wsdl">'
        f"<s:Header>{token}</s:Header>"
        "<s:Body>"
        "<ptz:ContinuousMove>"
        "<ptz:Position>"
        f"<ptz:PanTilt x='{pan:.6f}' y='{tilt:.6f}'/>"
        f"<ptz:Zoom x='{zoom:.6f}'/>"
        "</ptz:Position>"
        f"{speed_element}"
        f"</ptz:ContinuousMove>"
        "</s:Body>"
        "</s:Envelope>"
    )


def build_stop_move(token: str = "") -> str:
    """The ONVIF ``Stop`` request. Issued when a handoff is cancelled."""
    return (
        '<?xml version="1.0" encoding="UTF-8"?>'
        '<s:Envelope xmlns:s="http://www.w3.org/2003/05/soap-envelope"'
        ' xmlns:ptz="http://www.onvif.org/ver20/ptz/wsdl">'
        f"<s:Header>{token}</s:Header>"
        "<s:Body><ptz:Stop/></s:Body>"
        "</s:Envelope>"
    )


def _describe_options(ptz: Any, pan_delta: float, tilt_delta: float, zoom_ratio: float) -> str:
    """A readable ONVIF options string, for the operator-facing log."""
    parts = ["Space=Absolute"]
    if pan_delta > 60:
        parts.append(f"pan=PRESET(fast, {ptz.max_pan_speed_deg_s:.0f} deg/s)")
    elif pan_delta > 5:
        parts.append("pan=VELOCITY(medium)")
    if tilt_delta > 20:
        parts.append("tilt=VELOCITY(medium)")
    if zoom_ratio > 4:
        parts.append("zoom=VELOCITY(slow)")
    parts.append(f"dwell={ptz.settle_time_s:.2f}s")
    return " ".join(parts)


def _clamp(value: float, low: float, high: float) -> float:
    return float(max(min(value, high), low))


def compose_pan_series(
    start_deg: float,
    target_deg: float,
    *,
    max_step_deg: float = 170.0,
) -> list[float]:
    """Break a pan across the ONVIF ``[-1, 1]`` limit into a safe path.

    A single ``ContinuousMove`` may not accept a full 360-degree delta, so a large
    rotation is split at the wrap point. The unwrap keeps the intermediate values
    on a continuous branch rather than spinning the long way round.
    """
    delta = normalize_angle(math.radians(target_deg - start_deg)) * 180.0 / math.pi
    if abs(delta) <= max_step_deg:
        return [target_deg]

    steps: list[float] = []
    remaining = delta
    while abs(remaining) > max_step_deg:
        step = math.copysign(max_step_deg, remaining)
        steps.append(unwrap_bearing(0.0, math.radians(step)) * 180.0 / math.pi + start_deg)
        start_deg = steps[-1]
        remaining -= step
    steps.append(target_deg)
    return steps


def recoverable(camera_id: str, coverage: Any) -> bool:
    """Whether a camera can accept a recovery pre-position command at all."""
    view = coverage.view(camera_id)
    return view is not None and view.is_ptz


def all_idle(controller: PtzController) -> bool:
    return not controller.busy_cameras()


def command_summary(controller: PtzController) -> Sequence[dict[str, Any]]:
    return [c.to_dict() for c in controller.commands[-20:]]
