"""Typed configuration: schemas and loader.

Import from here rather than from :mod:`anti_uav.config.schema` directly, so a
schema rename does not fan out across the codebase.
"""

from __future__ import annotations

from .loader import (
    ConfigError,
    config_dir,
    config_path,
    detect_profile,
    invalidate,
    load,
    load_coverage_map,
    load_dataset,
    load_matrix,
    load_profile_override,
    load_recipe,
    load_registry,
    load_rules,
    load_settings,
    load_yaml,
    settings_with,
)
from .schema import (
    AppSettings,
    AugmentationSpec,
    CameraIntrinsics,
    CameraMount,
    CameraSpec,
    ClassMapping,
    ComboSpec,
    ConfidenceRule,
    CoverageMap,
    CrossCameraRule,
    DatasetRegistry,
    DatasetSpec,
    DownloadSource,
    DroneRules,
    ExperimentMatrix,
    Geofence,
    GpuProfile,
    IngestSpec,
    KinematicsRule,
    LossSpec,
    Modality,
    ModelFamily,
    OptimizerSpec,
    PersistenceRule,
    ProfileOverride,
    ProtectedZone,
    PTZCapabilities,
    RunPlan,
    SequenceGroupSpec,
    SourceKind,
    SpatialRule,
    TilingSpec,
    TrackerName,
    TrackingRule,
    TrainRecipe,
)

__all__ = [
    "AppSettings",
    "AugmentationSpec",
    "CameraIntrinsics",
    "CameraMount",
    "CameraSpec",
    "ClassMapping",
    "ComboSpec",
    "ConfidenceRule",
    "ConfigError",
    "CoverageMap",
    "CrossCameraRule",
    "DatasetRegistry",
    "DatasetSpec",
    "DownloadSource",
    "DroneRules",
    "ExperimentMatrix",
    "Geofence",
    "GpuProfile",
    "IngestSpec",
    "KinematicsRule",
    "LossSpec",
    "Modality",
    "ModelFamily",
    "OptimizerSpec",
    "PTZCapabilities",
    "PersistenceRule",
    "ProfileOverride",
    "ProtectedZone",
    "RunPlan",
    "SequenceGroupSpec",
    "SourceKind",
    "SpatialRule",
    "TilingSpec",
    "TrackerName",
    "TrackingRule",
    "TrainRecipe",
    "config_dir",
    "config_path",
    "detect_profile",
    "invalidate",
    "load",
    "load_coverage_map",
    "load_dataset",
    "load_matrix",
    "load_profile_override",
    "load_recipe",
    "load_registry",
    "load_rules",
    "load_settings",
    "load_yaml",
    "settings_with",
]
